services:
  mcp-server:
    image: ghcr.io/korotovsky/slack-mcp-server:latest
    restart: unless-stopped
    networks:
      - app-tier
    ports:
      - "3001:3001"
    # Optional: Uncomment to mount the CA certificate if you need to trust a custom CA
    # Don't forget to set SLACK_MCP_SERVER_CA=/usr/local/share/ca-certificates/ca.crt
    #
    # volumes:
    #   - ./ca-cert.crt:/usr/local/share/ca-certificates/ca.crt
    env_file:
      - .env
    environment:
      SLACK_MCP_HOST: "0.0.0.0"
      SLACK_MCP_PORT: "3001"

networks:
  app-tier:
    name: app-tier
    external: true
