services:
  mcp-server:
    build:
        context: .
        target: production
        dockerfile: Dockerfile
    # Uncomment to have delve debug on port 40000
    # command: /dlv debug /app/mcp/mcp-server.go --headless --listen=:40000 --api-version=2 --log -- --transport sse
    restart: unless-stopped
    networks:
      - app-tier
    ports:
      - "3001:3001"
      - "40000:40000"
    # Optional: Uncomment to mount the CA certificate if you need to trust a custom CA
    # Don't forget to set SLACK_MCP_SERVER_CA=/usr/local/share/ca-certificates/ca.crt
    #
    volumes:
      - ./ca-cert.crt:/usr/local/share/ca-certificates/ca.crt
    env_file:
      - .env
    environment:
      SLACK_MCP_HOST: "0.0.0.0"
      SLACK_MCP_PORT: "3001"
    extra_hosts:
     - "host.docker.internal:host-gateway"

networks:
  app-tier:
    name: app-tier
    external: true
