services:
  mcp-server:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-tier
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      SLACK_MCP_HOST: "0.0.0.0"
      SLACK_MCP_PORT: "3001"

networks:
  app-tier:
    name: app-tier
    external: true
